// resources/js/Components/TextInput.vue
<script setup>
import { onMounted, ref } from 'vue';

defineProps({
    modelValue: String,
});

defineEmits(['update:modelValue']);

const input = ref(null);

onMounted(() => {
    if (input.value.hasAttribute('autofocus')) {
        input.value.focus();
    }
});

defineExpose({ focus: () => input.value.focus() });
</script>

<template>
    <input
        ref="input"
        class="border-gray-300 focus:border-blue-500 focus:ring-blue-500 rounded-md shadow-sm text-gray-900"
        :value="modelValue"
        @input="$emit('update:modelValue', $event.target.value)"
    >
</template>

// resources/js/Components/TextInput.tsx
import React, { forwardRef, InputHTMLAttributes } from 'react';

export default forwardRef<HTMLInputElement, InputHTMLAttributes<HTMLInputElement>>(function TextInput(
    { type = 'text', className = '', ...props },
    ref
) {
    return (
        <input
            {...props}
            type={type}
            className={
                `border-gray-300 focus:border-blue-500 focus:ring-blue-500 rounded-lg shadow-sm text-sm text-gray-900 bg-white placeholder-gray-400 ${className}`
            }
            ref={ref}
        />
    );
});
